steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/sapient-zodiac-213700/testapp:$REVISION_ID", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/sapient-zodiac-213700/testapp:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - deployment/production
  - my-container=gcr.io/sapient-zodiac-213700/testapp:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-employsure-default-pool-b1828915-psr1'